sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

python:
   version: 3.7
   install:
      - requirements: requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
        path: another/package
   system_packages: true